name: Build game
on:
    push:
        tags:
            - "build*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Export Game
              uses: firebelley/godot-export@v6.0.0
              with:
                  godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
                  godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
                  relative_project_path: ./
                  archive_output: true
                  cache: true

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: game-build
                  path: ./builds/\
